os: linux
dist: xenial
language: node_js
node_js:
  - lts/*
before_install:
  - npm install -g codecov
  - npm install -g semantic-release
script:
  - nyc --reporter=lcov mocha && codecov
  - npx semantic-release
