name: Published
# trigger when a new tag is created
on:
  release:
    types:
      - created
      - edited
      - prereleased
      - released
      - published
      - unpublished
      - deleted

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: echo "This should be triggered when a release is published"
