name: Published
# trigger when a new tag is created
on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: echo "This should be triggered when a release is published"
