name: Published
# trigger when merging 'feature' branch to 'master'
on:
  pull_request:
    types: [closed]

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'feat*'}}
    # if: ${{ github.event.pull_request.title == 'feat*'}} && {{ github.event.pull_request.merged == true }}
    steps:
      - name: Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: echo "This should be triggered when a release is published"
