name: Dry Release
on:
  # on create a PR to 'master' branch
  pull_request:
    branches:
      - "master"
jobs:
  dry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Dry Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
