name: Dry Release
on:
  # on create a PR to 'main' branch
  pull_request:
    branches:
      - "main"
jobs:
  dry_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Dry Release
        run: npx semantic-release
